import axios from "axios";
import "dotenv/config";

// Generated by https://quicktype.io

export interface YouTubeVideoStatsResponseBody {
  kind: "youtube#videoListResponse";
  etag: string;
  items: Item[];
  pageInfo: PageInfo;
}

export interface Item {
  kind: "youtube#video";
  etag: string;
  id: string;
  statistics: Statistics;
}

export interface Statistics {
  viewCount: string;
  likeCount: string;
  favoriteCount: string;
  commentCount: string;
}

export interface PageInfo {
  totalResults: number;
  resultsPerPage: number;
}

const ax = () => {
  const config = {
    url: process.env.YOUTUBE_API_BASE_PATH,
  };
  const headers: { Accept?: string; Referrer?: string } = {
    Accept: "application/json",
  };

  if (process.env.NODE_ENV === "production") {
    headers.Referrer = process.env.YOUTUBE_API_REFERRER_PROD;
  }
  return axios.create(config);
};

export default async function getYouTubeStats(): Promise<YouTubeVideoStatsResponseBody> {
  try {
    const config = {
      method: "get",
      responseType: "stream",
      maxBodyLength: Infinity,
      url: "https://www.googleapis.com/youtube/v3/videos?key=AIzaSyDFJhvI7DZsUxXX1ryiUk_H9dF9aW81G-w&id=ypa8prwEMcc,eg7I8x-u0sc,_zWovo2zv6k,D-yskqXigZQ,T0F5hqXxGOk,PJMjHLzD_Kg,3yCKQ5b0st8,9QOpDGLLxIQ,-3nwwH9PgHA,wYrzc4AWCzw,O9lQGwKTEQM,IdtBkGQg2Q8,PeZ-Fz_soFs,1hs5e7TDwM4,fX5U50VGxtg,2Mkzy3ZWT6Q,fCbW1YFnm6M&part=statistics&maxResults=17",
      headers: {
        Accept: "application/json",
        Referer: "https://domz-devz.postman.co/",
      },
    };

    const response = await axios.request(config);
    const data = response.data;
    console.log(data);

    return data;
  } catch (error) {
    console.error(error);
    throw new Error("Couldn't get YouTube Stats", { cause: error });
  }
}
